allowBuilds:
  '@firebase/util': true
  core-js: true
  esbuild: true
  lefthook: true
  protobufjs: true

onlyBuiltDependencies:
  - '@firebase/util'
  - esbuild
  - lefthook

overrides:
  undici@<6.23.0: '>=6.23.0'
