/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TopRouteImport } from './routes/top'
import { Route as AnimeIdSlugRouteImport } from './routes/anime/$id/$slug'
import { Route as AnimeIdSlugIndexRouteImport } from './routes/anime/$id/$slug/index'
import { Route as AnimeIdSlugRecommendationsRouteImport } from './routes/anime/$id/$slug/recommendations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TopRoute = TopRouteImport.update({
  id: '/top',
  path: '/top',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIdSlugRoute = AnimeIdSlugRouteImport.update({
  id: '/anime/$id/$slug',
  path: '/anime/$id/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIdSlugIndexRoute = AnimeIdSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnimeIdSlugRoute,
} as any)
const AnimeIdSlugRecommendationsRoute =
  AnimeIdSlugRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AnimeIdSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/top': typeof TopRoute
  '/anime/$id/$slug': typeof AnimeIdSlugRouteWithChildren
  '/anime/$id/$slug/recommendations': typeof AnimeIdSlugRecommendationsRoute
  '/anime/$id/$slug/': typeof AnimeIdSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/top': typeof TopRoute
  '/anime/$id/$slug/recommendations': typeof AnimeIdSlugRecommendationsRoute
  '/anime/$id/$slug': typeof AnimeIdSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/top': typeof TopRoute
  '/anime/$id/$slug': typeof AnimeIdSlugRouteWithChildren
  '/anime/$id/$slug/recommendations': typeof AnimeIdSlugRecommendationsRoute
  '/anime/$id/$slug/': typeof AnimeIdSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/top'
    | '/anime/$id/$slug'
    | '/anime/$id/$slug/recommendations'
    | '/anime/$id/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/top'
    | '/anime/$id/$slug/recommendations'
    | '/anime/$id/$slug'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/top'
    | '/anime/$id/$slug'
    | '/anime/$id/$slug/recommendations'
    | '/anime/$id/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  TopRoute: typeof TopRoute
  AnimeIdSlugRoute: typeof AnimeIdSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top': {
      id: '/top'
      path: '/top'
      fullPath: '/top'
      preLoaderRoute: typeof TopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$id/$slug': {
      id: '/anime/$id/$slug'
      path: '/anime/$id/$slug'
      fullPath: '/anime/$id/$slug'
      preLoaderRoute: typeof AnimeIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$id/$slug/': {
      id: '/anime/$id/$slug/'
      path: '/'
      fullPath: '/anime/$id/$slug/'
      preLoaderRoute: typeof AnimeIdSlugIndexRouteImport
      parentRoute: typeof AnimeIdSlugRoute
    }
    '/anime/$id/$slug/recommendations': {
      id: '/anime/$id/$slug/recommendations'
      path: '/recommendations'
      fullPath: '/anime/$id/$slug/recommendations'
      preLoaderRoute: typeof AnimeIdSlugRecommendationsRouteImport
      parentRoute: typeof AnimeIdSlugRoute
    }
  }
}

interface AnimeIdSlugRouteChildren {
  AnimeIdSlugRecommendationsRoute: typeof AnimeIdSlugRecommendationsRoute
  AnimeIdSlugIndexRoute: typeof AnimeIdSlugIndexRoute
}

const AnimeIdSlugRouteChildren: AnimeIdSlugRouteChildren = {
  AnimeIdSlugRecommendationsRoute: AnimeIdSlugRecommendationsRoute,
  AnimeIdSlugIndexRoute: AnimeIdSlugIndexRoute,
}

const AnimeIdSlugRouteWithChildren = AnimeIdSlugRoute._addFileChildren(
  AnimeIdSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  TopRoute: TopRoute,
  AnimeIdSlugRoute: AnimeIdSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
